server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-service
  rabbitmq:
    host: 
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          # TODO : 설정 파일들 name 달아서 넣으면됨
          # Window 일 경우에는 마지막에 / 붙여야함
          search-locations: classpath:/configs

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
